'use client';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, Car, ChevronRight, Clock3, MapPin, Menu, Moon, Search, Sun, Train, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Place={name:string; area:string; desc:string; duration:string; score:string; note:string; map:string; image?:string; price?:string; dish?:string};
const places:Place[]=[
 {name:'しらすや（吻仔魚屋）',area:'腰越',desc:'江之電腰越站附近的名店，是鎌倉行程中安排午餐的第一選擇。',duration:'用餐 45–60 分',score:'必吃',note:'午餐時段建議預留候位時間；也可改選 PIGGY HOUSE。',map:'https://www.google.com/maps/search/?api=1&query=Shirasuya+Koshigoe',price:'未記錄',dish:'吻仔魚料理'},
 {name:'鎌倉高校前',area:'七里濱',desc:'江之電沿海路線最具代表性的停靠點，適合感受湘南海岸與鐵道交會的畫面。',duration:'20–30 分',score:'必去',note:'拍照時請留意列車、號誌與周邊住戶，勿進入軌道或妨礙交通。',map:'https://www.google.com/maps/search/?api=1&query=Kamakurakokomae+Station'},
 {name:'bills 七里濱',area:'七里濱',desc:'面向湘南海岸的休息點；原始行程特別標記鬆餅。',duration:'60–90 分',score:'推薦',note:'午後熱門，若只想看海可斟酌候位時間。',map:'https://www.google.com/maps/search/?api=1&query=bills+Shichirigahama',price:'未記錄',dish:'鬆餅'},
 {name:'高德院・鎌倉大佛',area:'長谷',desc:'鎌倉最經典的歷史景點，適合作為海岸段之後的文化停留。',duration:'45–60 分',score:'必去',note:'由七里濱往長谷的動線可直接搭江之電。',map:'https://www.google.com/maps/search/?api=1&query=Kotokuin+Great+Buddha'},
 {name:'小町通',area:'鎌倉站',desc:'從鎌倉站延伸的散步商店街，可安排逛街、點心與伴手禮。',duration:'45–60 分',score:'推薦',note:'和鶴岡八幡宮適合排在同一段，傍晚人潮較集中。',map:'https://www.google.com/maps/search/?api=1&query=Komachi+dori+Kamakura'},
 {name:'鶴岡八幡宮',area:'鎌倉站',desc:'鎌倉中心的重要神社，與小町通相連，適合以步行探索。',duration:'45–60 分',score:'必去',note:'原行程安排在小町通之後；請依當日開放時間調整。',map:'https://www.google.com/maps/search/?api=1&query=Tsurugaoka+Hachimangu'},
 {name:'材木座テラス',area:'材木座',desc:'原行程標記為喝咖啡的海邊休息點。',duration:'30–45 分',score:'可選',note:'適合作為鎌倉市區段結束前的放鬆停留。',map:'https://www.google.com/maps/search/?api=1&query=Zaimokuza+Terrace'},
 {name:'江之島老街・弁天橋',area:'江之島',desc:'從江之島站穿越弁天橋進入老街，原計畫以日落為收尾。',duration:'60–90 分',score:'推薦',note:'若鎌倉市區逛得較久，可把水族館列為彈性選項。',map:'https://www.google.com/maps/search/?api=1&query=Enoshima+Bentenbashi'},
 {name:'新江ノ島水族館',area:'江之島',desc:'江之島海岸旁的水族館，適合有餘裕時加入。',duration:'90–120 分',score:'彈性',note:'原始行程註記「如果有時間」，不建議硬塞進緊湊的一日行程。',map:'https://www.google.com/maps/search/?api=1&query=Enoshima+Aquarium'}
];
const days=[['8/11','淺草・晴空塔','合羽橋道具街 → 淺草寺 → 晴空塔'],['8/12','川越・吉祥寺・東京車站','一番街、時之鐘、菓子屋橫丁、冰川神社'],['8/13','輕井澤單車','雲場池、星野區、舊輕井澤、Outlet'],['8/14','江之島・鎌倉','湘南單軌、江之電、海岸、長谷、鎌倉站'],['8/15','橫濱港未來','空中纜車、Cosmo World、Marine & Walk、中華街'],['8/16','豐洲・台場','豐洲市場、DECKS、Aqua City、DiverCity'],['8/17','河口湖包車','全天包車行程'],['8/18','橫濱','保留彈性的一天'],['8/19','上野・阿美橫丁','上野動物園、阿美橫丁、前往機場']];
const nearby=[['鎌倉・江之島','海、江之電與古都的一日組合。','1 日','#kamakura'],['川越','小江戶散步與冰川神社。','半日～1 日','#history'],['輕井澤','新幹線與單車串連星野區和舊輕井澤。','1 日','#history'],['橫濱','港未來空中纜車與中華街。','1 日','#itinerary'],['河口湖','原始行程採用全天包車。','1 日','#tokyo-notes']];
const historic=[['Day 1 · 10/6','淺草','CI-220 松山至羽田；關東廣域周遊券、MIMARU 上野東、雷門與淺草炸牛排。'],['Day 2 · 10/7','川越','一番街、時之鐘、菓子屋橫丁、林屋鰻魚飯、冰川神社與小江戶蔵里。'],['Day 3 · 10/8','輕井澤','雲場池、丸山咖啡、星野區、舊輕井澤銀座、Prince Outlet。'],['Day 4 · 10/9','江之島・鎌倉','另保留極樂寺站作為長谷段可選停靠。'],['Day 5 · 10/10','上野・阿美橫丁','上野公園、動物園、阿美橫丁與 CI-109 回台。']];
const timeline=[['08:00','上野出發','JR 宇都宮線／高崎線前往大船'],['09:00','大船站','購買 JR 鎌倉・江之島 Pass'],['10:30','湘南江之島','搭湘南單軌，轉乘江之電'],['11:00','腰越午餐','しらすや 吻仔魚屋／PIGGY HOUSE'],['12:00','鎌倉高校前','海岸與江之電路段'],['13:00','七里濱','bills 鬆餅、看海休息'],['14:00','長谷','高德院・鎌倉大佛'],['16:00','鎌倉站','小町通 → 鶴岡八幡宮 → 材木座咖啡'],['16:30','江之島','弁天橋、老街與日落；水族館視時間'],['18:00','辻堂','Terrace Mall 湘南晚餐後經藤澤回上野']];
const articles=[
 ['東京灣一日順路玩法','築地 → 豐洲 → 有明 → 台場。早上吃海鮮、午後購物，晚上在台場看夜景與晚餐。','https://article-image.travel.navitime.jp/img/NTJarea0120-zh-tw/chizu.jpg'],
 ['Small Worlds 微縮模型樂園','有明的世界最大微縮模型樂園：六大展區，含美少女戰士、EVA、關西機場、宇宙中心與世界之街。每 30 分鐘有約 5 分鐘火箭發射秀。','https://article-image.travel.navitime.jp/img/NTJnews0301-zh-tw/0.jpg'],
 ['東京包車備註','東京市區、富士山與箱根可採客製包車；原始筆記：箱根富士山最便宜。','']
];
function MapLink({href}:{href:string}) { return (<a href={href} target="_blank" className="inline-flex items-center gap-1 text-sm font-semibold text-coral hover:underline">Google Map <ArrowUpRight size={15} /></a>); }
export default function Home() {
 const [dark,setDark] = useState(false);
 const [q,setQ] = useState('');
 const [menu,setMenu] = useState(false);
 useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
 const results = useMemo(() => places.filter((x) => (`${x.name} ${x.area} ${x.desc} ${x.note}`).toLowerCase().includes(q.toLowerCase())), [q]);
 const nav = [['快速開始','start'],['近郊','nearby'],['行程','itinerary'],['鎌倉','kamakura'],['美食','food'],['地圖','maps'],['FAQ','faq']];
 return (<main>
 <header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[color:var(--bg)]/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><a href="#top" className="font-bold tracking-tight">Tokyo <span className="text-coral">Guide</span></a><nav className="hidden gap-5 md:flex">{nav.map(([n,id])=><a className="navlink" href={'#'+id} key={id}>{n}</a>)}</nav><div className="flex items-center gap-2"><button onClick={()=>setDark(!dark)} className="rounded-full p-2 hover:bg-black/5 dark:hover:bg-white/10" aria-label="切換深色模式">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={()=>setMenu(!menu)} className="rounded-full p-2 md:hidden">{menu?<X/>:<Menu/>}</button></div></div>{menu&&<div className="border-t border-[var(--line)] px-5 pb-4 md:hidden">{nav.map(([n,id])=><a onClick={()=>setMenu(false)} className="block py-2 text-sm" href={'#'+id} key={id}>{n}</a>)}</div>}</header>
 <section id="top" className="relative overflow-hidden"><div className="absolute inset-0 image-placeholder opacity-80"/><div className="absolute inset-0 bg-gradient-to-b from-white/10 via-white/35 to-[var(--bg)] dark:from-black/10 dark:via-black/30"/><div className="relative mx-auto max-w-6xl px-5 pb-24 pt-24 md:pb-32 md:pt-36"><motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="eyebrow">Tokyo & nearby · curated</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="mt-4 max-w-3xl text-5xl font-bold tracking-[-.06em] md:text-7xl">東京與近郊<br/>自由行 Guide</motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.16}} className="mt-6 max-w-xl text-lg leading-8 text-[var(--muted)]">這是一份整理多年旅遊經驗的東京旅行指南。從經典市區到鎌倉、川越、輕井澤、橫濱與河口湖，把真正會用到的路線、交通與停留節奏收進同一本 Guide。</motion.p><a href="#nearby" className="mt-8 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5">探索東京近郊 <ChevronRight size={16}/></a></div></section>
 <section id="start" className="mx-auto max-w-6xl px-5 py-20"><p className="eyebrow">Quick start</p><h2 className="mt-3 text-3xl font-bold tracking-tight">用這份 Guide 開始規劃</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[['最適合','第一次東京自由行，想兼顧經典景點與一日近郊。'],['鎌倉建議','一整天；不要把江之島、水族館與所有鎌倉點硬塞。'],['行前提醒','交通班次、店家營業時間與票券規則，出發前再確認。']].map(([a,b])=><div className="card p-6" key={a}><p className="font-bold">{a}</p><p className="muted mt-3 text-sm leading-6">{b}</p></div>)}</div></section>
 <section id="nearby" className="mx-auto max-w-6xl px-5 py-20"><p className="eyebrow">Day trips</p><h2 className="mt-3 text-3xl font-bold tracking-tight">東京為中心，延伸五個方向</h2><p className="muted mt-3 max-w-2xl leading-7">同一間東京住宿，也可以用一天一個主題來安排近郊。這裡依原始資料的成熟動線整理，保留景點與轉乘脈絡。</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{nearby.map(([a,b,c,href])=><a href={href} className="card group p-6 transition hover:-translate-y-1" key={a}><p className="text-xs font-bold text-coral">{c}</p><h3 className="mt-2 text-xl font-bold">{a}</h3><p className="muted mt-3 text-sm leading-6">{b}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold">查看路線 <ChevronRight size={15}/></span></a>)}</div></section>
 <section id="itinerary" className="mx-auto max-w-6xl px-5 py-16"><p className="eyebrow">Itinerary</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl font-bold tracking-tight">9 日東京家庭自由行</h2><p className="muted text-sm">2023 年 8 月 · 住宿：MIMARU Ueno East</p></div><div className="mt-8 grid gap-3 md:grid-cols-3">{days.map(d=><div key={d[0]} className="card p-5"><p className="text-sm font-bold text-coral">{d[0]}</p><h3 className="mt-2 font-bold">{d[1]}</h3><p className="muted mt-2 text-sm leading-6">{d[2]}</p></div>)}</div></section>
 <section id="kamakura" className="border-y border-[var(--line)] bg-white/35 py-20 dark:bg-white/[.02]"><div className="mx-auto max-w-6xl px-5"><p className="eyebrow">Kamakura chapter</p><h2 className="mt-3 text-4xl font-bold tracking-tight">把一天交給海、鐵道與古都。</h2><p className="muted mt-4 max-w-2xl leading-7">鎌倉最值得的不是打卡清單，而是江之電沿海移動的節奏：上午從大船進入湘南，午後在長谷與鎌倉站回到古都，傍晚再到江之島看海。</p><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['特色','海岸、江之電、神社寺院與商店街在同一天相遇'],['停留時間','建議完整 1 日'],['推薦季節','天氣穩定、日照較長時更能享受海岸段'],['適合族群','初訪東京、喜歡步行／鐵道／海景的旅人']].map(([a,b])=><div className="card p-5" key={a}><p className="text-sm font-bold">{a}</p><p className="muted mt-2 text-sm leading-6">{b}</p></div>)}</div></div></section>
 <section className="mx-auto max-w-6xl px-5 py-20"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Places</p><h2 className="mt-3 text-3xl font-bold tracking-tight">鎌倉景點</h2></div><label className="relative"><Search size={17} className="absolute left-3 top-3 text-[var(--muted)]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋景點、區域…" className="w-64 rounded-full border border-[var(--line)] bg-transparent py-2.5 pl-9 pr-4 text-sm outline-none focus:ring-2 focus:ring-coral/30"/></label></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><AnimatePresence>{results.map((p,i)=><motion.article initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{delay:i*.025}} className="card overflow-hidden" key={p.name}><div className="image-placeholder flex h-36 items-end p-4"><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-bold text-slate-700">{p.area}</span></div><div className="p-6"><div className="flex justify-between gap-2"><h3 className="font-bold">{p.name}</h3><span className="whitespace-nowrap text-xs font-bold text-coral">{p.score}</span></div><p className="muted mt-3 text-sm leading-6">{p.desc}</p><div className="mt-4 flex items-center gap-2 text-xs text-[var(--muted)]"><Clock3 size={14}/>{p.duration}</div><p className="mt-4 border-l-2 border-coral pl-3 text-sm leading-6"><b>我的建議</b>　{p.note}</p><div className="mt-5"><MapLink href={p.map}/></div></div></motion.article>)}</AnimatePresence></div></section>
 <section id="food" className="mx-auto max-w-6xl px-5 py-12"><p className="eyebrow">Food</p><h2 className="mt-3 text-3xl font-bold tracking-tight">鎌倉吃什麼</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{places.filter(x=>x.dish).map(p=><div className="card p-6" key={p.name}><p className="font-bold">{p.name}</p><p className="muted mt-3 text-sm">推薦：{p.dish}</p><p className="muted mt-1 text-sm">價格：{p.price}</p><div className="mt-5"><MapLink href={p.map}/></div></div>)}</div></section>
 <section className="mx-auto max-w-6xl px-5 py-20"><p className="eyebrow">Getting around</p><h2 className="mt-3 text-3xl font-bold tracking-tight">交通：順著路線移動</h2><div className="mt-8 grid gap-4 md:grid-cols-5">{[[Train,'JR','上野 → 大船；原行程在大船購買鎌倉・江之島 Pass'],[Train,'湘南單軌','大船 → 湘南江之島，接上沿海行程'],[Train,'江之電','湘南江之島、腰越、鎌倉高校前、七里濱、長谷、鎌倉'],[Car,'停車／自駕','原始資料未提供鎌倉停車資訊；熱門海岸與車站周邊先查停車位與費率'],[MapPin,'步行','小町通與鶴岡八幡宮可連續步行；預留海岸散步時間']].map(([Icon,a,b])=><div className="card p-5" key={a as string}><Icon size={19} className="text-coral"/><p className="mt-4 font-bold">{a as string}</p><p className="muted mt-2 text-sm leading-6">{b as string}</p></div>)}</div></section>
 <section className="mx-auto max-w-4xl px-5 py-16"><p className="eyebrow">My route</p><h2 className="mt-3 text-3xl font-bold tracking-tight">我的建議路線</h2><div className="mt-8 border-l border-[var(--line)] pl-6">{timeline.map(([t,a,b])=><div className="relative pb-8" key={t+a}><i className="absolute -left-[31px] top-1 h-3 w-3 rounded-full bg-coral ring-4 ring-[var(--bg)]"/><p className="text-sm font-bold text-coral">{t}</p><h3 className="mt-1 font-bold">{a}</h3><p className="muted mt-1 text-sm">{b}</p></div>)}</div></section>
 <section id="maps" className="mx-auto max-w-6xl px-5 py-16"><p className="eyebrow">Maps</p><h2 className="mt-3 text-3xl font-bold tracking-tight">所有地點，一次開啟</h2><div className="mt-8 card p-6"><div className="grid gap-x-8 gap-y-3 sm:grid-cols-2 lg:grid-cols-3">{places.map(p=><MapLink key={p.name} href={p.map}/>)}</div></div></section>
 <section id="history" className="mx-auto max-w-6xl px-5 py-20"><p className="eyebrow">Travel archive</p><h2 className="mt-3 text-3xl font-bold tracking-tight">2018 行程細節：近郊路線的原始版本</h2><p className="muted mt-3 max-w-2xl text-sm leading-6">保留原始行程的時間、替代交通、餐廳與航班記錄；這些內容已融入上方 Guide，也能在此回查完整脈絡。</p><div className="mt-8 grid gap-4 md:grid-cols-2">{historic.map(([a,b,c])=><article className="card p-6" key={a}><p className="text-sm font-bold text-coral">{a}</p><h3 className="mt-2 font-bold">{b}</h3><p className="muted mt-3 text-sm leading-7">{c}</p></article>)}</div></section>
 <section id="tokyo-notes" className="mx-auto max-w-6xl px-5 py-16"><p className="eyebrow">Tokyo extras</p><h2 className="mt-3 text-3xl font-bold tracking-tight">原始筆記中的東京補充</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{articles.map(([a,b,img])=><article className="card overflow-hidden" key={a}>{img?<img loading="lazy" src={img} alt="" className="h-36 w-full object-cover"/>:<div className="image-placeholder h-36"/>}<div className="p-6"><h3 className="font-bold">{a}</h3><p className="muted mt-3 text-sm leading-6">{b}</p></div></article>)}</div></section>
 <section id="faq" className="mx-auto max-w-4xl px-5 py-20"><p className="eyebrow">Tips & FAQ</p><h2 className="mt-3 text-3xl font-bold tracking-tight">出發前，先記住這幾件事</h2><div className="mt-8 space-y-3">{[['鎌倉一天夠嗎？','夠，但須取捨。把江之島老街與新江之島水族館視為彈性項目，才能保有散步與候位的空間。'],['怎麼避開人潮？','早一點從上野出發，午餐店與 bills 都可能需等候；熱門拍攝點以安全與不妨礙交通優先。'],['哪些地方最適合拍照？','鎌倉高校前、七里濱海岸、江之島的弁天橋與日落；請遵守現場規範。'],['票券需要注意什麼？','原行程使用 JR 鎌倉・江之島 Pass。票券內容與售價可能調整，出發前請確認官方最新規則。']].map(([q,a])=><details className="card p-5" key={q}><summary className="cursor-pointer font-bold">{q}</summary><p className="muted mt-3 text-sm leading-6">{a}</p></details>)}</div></section>
 <footer className="border-t border-[var(--line)] px-5 py-10 text-center text-sm text-[var(--muted)]">Tokyo Guide · 整理自 2023 東京家庭自由行 Notion 匯出資料</footer>
 </main>)}
